[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[features]
verbose_solids = []

#[patch.crates-io]
#egui = { git = "../egui", branch = "button_click_bug" }

[dependencies]
# eframe uses glow 0.12.0
#glow = "0.12.0"
#glutin = "0.31.0"
serde_json = "1.0.81"
#memoffset = "0.9.0"
egui = "0.23.0"
#egui_glow = "0.23.0"
#eframe = "0.23.0"
#by_address = "1.1.0"
# uuid = { version = "1.1.2", features = ["v4"] }
image = "0.24.7"
#walkdir = "2.4.0"
itertools = "0.11.0"
# approx = "0.5.1"
petgraph = "0.6.4"
arboard = "3.2.1"
#weak-table = "0.3.2"
bytemuck = { version = "1.14.0", features = ["derive"] }
data-encoding = "2.4.0"
smallvec = { version = "1.11.1", features = ["union", "const_generics", "const_new"] }
# num-integer = { version = "0.1.45", features = ["i128"] }
bimap = "0.6.3"
num-traits = "0.2.17"
anyhow = { version = "1.0.75", features = ["backtrace"] }
hex = "0.4.3"
arrayvec = "0.7.4"
# dlv-list = "0.5.1"
# fastrand = "2.0.1"

[profile.release]
debug = 1
