[package]
name = "seamlang_bin"
version = "0.1.0"
edition = "2021"

[lib]
name = "seamlang"
crate-type = ["cdylib", "rlib"]

[patch.crates-io]
eframe = { git = "https://github.com/tneukom/egui_seamlang.git", branch = "tne/no_gl_clear" }
egui = { git = "https://github.com/tneukom/egui_seamlang.git", branch = "tne/no_gl_clear" }
egui_glow = { git = "https://github.com/tneukom/egui_seamlang.git", branch = "tne/no_gl_clear" }


[dependencies]
wasm-bindgen = "0.2.63"
eframe = { version = "0.25.0", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow", # Use the glow rendering backend. Alternative: "wgpu".
    "persistence", # Enable restoring app state when restarting the app.
] }
egui = { version = "0.25.0" }
egui_glow = { version = "0.25.0" }
glow = "0.13.1"
wasm-bindgen-futures = "0.4"
log = "0.4"

# eframe uses glow 0.12.0

#glutin = "0.31.0"
#serde_json = "1.0.81"
memoffset = "0.9.0"
by_address = "1.1.0"
image = { version = "0.24.8", default-features = false, features = [ "png" ] }
itertools = "0.12.1"
petgraph = "0.6.4"
#arboard = "3.2.1"
#weak-table = "0.3.2"
bytemuck = { version = "1.14.3", features = ["derive"] }
data-encoding = "2.5.0"
smallvec = { version = "1.13.1", features = ["union", "const_generics", "const_new"] }
# num-integer = { version = "0.1.45", features = ["i128"] }
bimap = "0.6.3"
num-traits = "0.2.18"
anyhow = { version = "1.0.79", features = ["backtrace"] }
hex = "0.4.3"
arrayvec = "0.7.4"
pretty_assertions = "1.4.0"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
#slotmap = "1.0.7"
# dlv-list = "0.5.1"
# fastrand = "2.0.1"

[profile.release]
debug = 1
